---
model:
    class: Audio1DConvCat
    config:
        lr: 0.01
        raw_audio_extractor_units:
            -
                channels: 1
                kernel_size: 128
                pool:
                    kernel_size: 9
                    stride: 3
            - 
                channels: 64
                kernel_size: 64
                pool:
                    kernel_size: 9
                    stride: 3
            - 
                channels: 64
                kernel_size: 32
                pool:
                    kernel_size: 9
                    stride: 3
            - 
                channels: 64
                kernel_size: 16
                pool:
                    kernel_size: 9
                    stride: 3
            - 128
        raw_audio_latent_time_units: 32
        classifier_units:
            - 512
            - 256
            - 128
    sample_input: [1, 1, 110250]
dataset:
    class: BaseAudioOnlyChunkedDataset
    name: mer-taffc
    temp_prefix: i-a-o-cat
    # split_dir: xxx
    data_dir_postfix: audio
    config:
        sr: 22050
        chunk_duration: 5
        # duration: 5
        overlap: 2.5
        force_compute: false
        audio_extension: mp3
kfold:
    n_splits: 5
    stratify: false
    batch_size: 16
    num_workers: 4
    # max_runs: null
    wandb_tags:
        - input:A
        - output:Cat
    model_monitor: val/loss
    early_stop_monitor: val/loss
    early_stop_mode: min
    gpus: -1
    max_epochs: 100