data:
  dataset: mer-taffc
  split: 60-20-20
  temp_folder: a_mer-taffc_s
  sub_folder: audio
model:
  version: 1
  params:
    lr: 0.001
    optimizer: "adam"
    weight_decay: 0.000001
    momentum: 0
    dropout: 0.5
    std_activation: "relu"
    adaptive_layer_units_0: 1
    adaptive_layer_units_1: 2
    n_fft: 1024
    n_mels: 128
    n_mfcc: 20
    spec_trainable: true
batch_size: 128