data:
  dataset: pmemo
  split: kfold
  temp_folder: a_pmemo
  sub_folder: audio
model:
  version: 1
  params:
    adaptive_layer_units: 4
    dropout: 0.15
    lr: 0.0005
    momentum: 0
    n_fft: 1024
    n_mels: 128
    n_mfcc: 20
    optimizer: "adam"
    spec_trainable: false
    std_activation: "relu"
    weight_decay: 0.00001
batch_size: 128