data:
  dataset: mer-taffc
  split: kfold
  temp_folder: a_mer-taffc
  sub_folder: audio
model:
  version: 1
  params:
    lr: 0.01
    optimizer: "sgd"
    weight_decay: 0.00001
    momentum: 0.95
    dropout: 0.5
    adaptive_layer_units_0: 1
    adaptive_layer_units_1: 4
batch_size: 128