data:
  dataset: pmemo
  split: 60-20-20
  temp_folder: a_pmemo
  sub_folder: audio
model:
  version: 1
  params:
    lr: 0.001
    optimizer: "adam"
    weight_decay: 0.001
    momentum: 0
    dropout: 0.5
    std_activation: "relu"
    adaptive_layer_units: 1
batch_size: 128