data:
  dataset: pmemo
  split: kfold
  temp_folder: a_pmemo
  sub_folder: audio
model:
  version: 1
  params:
    dropout: 0.15
    lr: 0.01
    momentum: 0.95
    n_fft: 1024
    n_mels: 128
    n_mfcc: 20
    optimizer: "adam"
    spec_trainable: false
    std_activation: "relu"
    weight_decay: 0.00001
    mel_spec_hidden_size: 150
    mel_spec_num_layers: 2
    mfcc_hidden_size: 16
    mfcc_num_layers: 1
    stft_hidden_size: 32
    stft_num_layers: 2
batch_size: 128