data:
  dataset: pmemo
  split: 60-20-20
  temp_folder: al_pmemo
  sub_folder: ""
model:
  version: 1
  params:
    lr: 0.001
    optimizer: "adam"
    weight_decay: 0.001
    momentum: 0
    dropout: 0.5
    adaptive_layer_units: 1
    n_fft: 1024
    n_mels: 128
    n_mfcc: 20
    n_cqt: 84
    spec_trainable: true
batch_size: 128