data:
  dataset: pmemo
  split: kfold
  temp_folder: a_pmemo
  sub_folder: audio
model:
  version: 1
  params:
    adaptive_layer_units: 4
    dropout: 0.2
    lr: 0.01
    momentum: 0
    n_fft: 1024
    n_mels: 128
    n_mfcc: 20
    optimizer: "adam"
    spec_trainable: true
    std_activation: "relu"
    weight_decay: 0.000001
batch_size: 128