data:
  dataset: pmemo
  split: kfold
  temp_folder: al_pmemo
  sub_folder: .
model:
  version: 1
  params:
    adaptive_layer_units_0: 8
    adaptive_layer_units_1: 16
    dropout: 0.2
    lr: 0.0001
    n_fft: 1024
    n_mels: 128
    n_mfcc: 20
    optimizer: "adam"
    spec_trainable: true
    std_activation: "softplus"
    weight_decay: 0.000001
batch_size: 64