data:
  dataset: deam
  split: kfold
  temp_folder: a_deam
  sub_folder: audio
model:
  version: 1
  params:
    adaptive_layer_units_0: 2
    adaptive_layer_units_1: 4
    dropout: 0.15
    lr: 0.0005
    momentum: 0.9
    n_fft: 1024
    n_mels: 128
    n_mfcc: 20
    optimizer: "sgd"
    spec_trainable: true
    std_activation: "softplus"
    weight_decay: 0.0000001
batch_size: 128