data:
  dataset: deam
  split: 60-20-20
  temp_folder: a_deam
model:
  version: 1
  params:
    lr: 0.001
    optimizer: "adam"
    weight_decay: 0.001
    momentum: 0
    dropout: 0.5
batch_size: 128