data:
  dataset: mer-taffc
  split: kfold
  temp_folder: a_mer-taffc
  sub_folder: audio
model:
  version: 1
  params:
    lr: 0.001
    optimizer: "adam"
    weight_decay: 0.00001
    momentum: 0.8
    dropout: 0.25
    adaptive_layer_units: 8
    n_fft: 1024
    n_mels: 128
    n_mfcc: 20
    spec_trainable: true
batch_size: 128