data:
  dataset: mer-taffc
  split: 60-20-20
  temp_folder: a_mer-taffc
  sub_folder: audio
model:
  version: 2
  params:
    lr: 0.001
    optimizer: "adam"
    weight_decay: 0.001
    momentum: 0
    dropout: 0.5
    adaptive_layer_units: 1
    n_fft: 1024
    n_mels: 128
    n_mfcc: 20
    n_cqt: 84
    spec_trainable: true
batch_size: 128