data:
  dataset: pmemo
  split: kfold
  temp_folder: al_pmemo
  sub_folder: .
model:
  version: 1
  params:
    adaptive_layer_units_0: 2
    adaptive_layer_units_1: 4
    dropout: 0.25
    lr: 0.01
    n_fft: 1024
    n_mels: 128
    n_mfcc: 20
    optimizer: "adam"
    spec_trainable: true
    std_activation: "softplus"
    weight_decay: 0.00001
batch_size: 128