wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      4: 3.8.8
      5: 0.10.27
      8:
      - 3
      - 5
adaptive_layer:
  desc: null
  value: 128
conv1_kernel_size:
  desc: null
  value: 11025
conv1_kernel_stride:
  desc: null
  value: 400
lr:
  desc: null
  value: 0.001
max_epochs:
  desc: null
  value: 100
